"""
Generate KWS constants — uses torchaudio directly for 100% identical values.
"""
import numpy as np
import torch
import torchaudio
from pathlib import Path

SAMPLE_RATE = 16000
N_FFT = 512
N_MELS = 40
WIN_LEN = 480
HOP_LEN = 160
F_MIN = 20.0
F_MAX = 8000.0


def generate():
    # --- Hann window (periodic, torch default) ---
    win = torch.hann_window(WIN_LEN, periodic=True).numpy().astype(np.float32)

    # --- Mel filterbank (use torchaudio directly for 100% match) ---
    # torchaudio's MelScale with norm=None (default for MelSpectrogram)
    mel_scale = torchaudio.transforms.MelScale(
        n_mels=N_MELS, sample_rate=SAMPLE_RATE,
        f_min=F_MIN, f_max=F_MAX,
        n_stft=N_FFT // 2 + 1,
        norm=None, mel_scale='htk')
    # fb shape: (n_stft, n_mels) = (257, 40)
    fb = mel_scale.fb.numpy().astype(np.float32)

    # --- Write header ---
    out_path = Path(__file__).parent.parent / \
        "AGV_H753_Master/Core/Inc/kws_constants.h"

    lines = [
        "// Auto-generated: Hann window + Mel filterbank (torchaudio exact match)",
        "// Generated by training/generate_kws_constants.py",
        "#ifndef __KWS_CONSTANTS_H",
        "#define __KWS_CONSTANTS_H",
        "",
        "#include <stdint.h>",
        "",
        f"#define KWS_N_FFT      {N_FFT}",
        f"#define KWS_N_MELS     {N_MELS}",
        f"#define KWS_WIN_LEN    {WIN_LEN}",
        f"#define KWS_HOP_LEN    {HOP_LEN}",
        f"#define KWS_SAMPLE_RATE {SAMPLE_RATE}",
        f"#define KWS_FFT_BINS   {N_FFT // 2 + 1}",
        "",
        "// Hann window (float32, length 480)",
        "static const float kws_hann_window[KWS_WIN_LEN] = {",
    ]

    for i in range(0, WIN_LEN, 8):
        vals = ", ".join(f"{win[j]:.10f}f" for j in range(i, min(i + 8, WIN_LEN)))
        lines.append(f"    {vals},")

    lines.append("};")
    lines.append("")
    lines.append(
        "// Mel filterbank matrix [257][40] (float32, torchaudio exact)")
    lines.append("static const float kws_mel_fbank[257][40] = {")

    for i in range(257):
        vals = ", ".join(f"{fb[i, j]:.10f}f" for j in range(N_MELS))
        lines.append(f"    {{{vals}}},")

    lines.append("};")
    lines.append("")
    lines.append("#endif /* __KWS_CONSTANTS_H */")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, 'w') as f:
        f.write('\n'.join(lines) + '\n')

    print(f"Generated: {out_path}")
    print(f"  Hann window: {WIN_LEN} samples")
    print(f"  Mel filterbank: 257x{N_MELS}")
    print(f"  Total Flash:     ~{(WIN_LEN + 257*N_MELS)*4/1024:.1f} KB")


if __name__ == '__main__':
    generate()
