"""
Generate KWS constants for MCU (Mel filterbank + Hamming window)
→ AGV_H753_Master/Core/Inc/kws_constants.h
"""
import numpy as np
from pathlib import Path

SAMPLE_RATE = 16000
N_FFT = 512
N_MELS = 40
WIN_LEN = int(0.030 * SAMPLE_RATE)  # 480
HOP_LEN = int(0.010 * SAMPLE_RATE)  # 160
F_MIN = 20.0
F_MAX = SAMPLE_RATE / 2


def hz_to_mel(hz):
    return 2595.0 * np.log10(1.0 + hz / 700.0)


def mel_to_hz(mel):
    return 700.0 * (10.0 ** (mel / 2595.0) - 1.0)


def generate():
    # --- Hamming window ---
    hamming = np.hamming(WIN_LEN).astype(np.float32)

    # --- Mel filterbank ---
    mel_min = hz_to_mel(F_MIN)
    mel_max = hz_to_mel(F_MAX)
    mel_pts = np.linspace(mel_min, mel_max, N_MELS + 2)
    freq_pts = mel_to_hz(mel_pts)
    bin_pts = np.floor((N_FFT + 1) * freq_pts / SAMPLE_RATE).astype(int)

    filterbank = np.zeros((N_MELS, N_FFT // 2 + 1), dtype=np.float32)
    for m in range(N_MELS):
        left = bin_pts[m]
        center = bin_pts[m + 1]
        right = bin_pts[m + 2]
        for k in range(left, center):
            filterbank[m, k] = (k - left) / max(1, center - left)
        for k in range(center, right):
            filterbank[m, k] = (right - k) / max(1, right - center)
        # Normalize by filter width
        width = right - left
        if width > 0:
            filterbank[m] /= width

    filterbank_T = filterbank.T  # (257, 40) for matrix multiply

    # --- Write header ---
    out_path = Path(__file__).parent.parent / \
        "AGV_H753_Master/Core/Inc/kws_constants.h"

    lines = [
        "// Auto-generated Mel filterbank + Hamming window for KWS",
        "// Generated by training/generate_kws_constants.py",
        "#ifndef __KWS_CONSTANTS_H",
        "#define __KWS_CONSTANTS_H",
        "",
        "#include <stdint.h>",
        "",
        f"#define KWS_N_FFT      {N_FFT}",
        f"#define KWS_N_MELS     {N_MELS}",
        f"#define KWS_WIN_LEN    {WIN_LEN}",
        f"#define KWS_HOP_LEN    {HOP_LEN}",
        f"#define KWS_SAMPLE_RATE {SAMPLE_RATE}",
        f"#define KWS_FFT_BINS   {N_FFT // 2 + 1}",
        "",
        "// Hamming window (float32, length 480)",
        "static const float kws_hamming_window[KWS_WIN_LEN] = {",
    ]

    for i in range(0, WIN_LEN, 8):
        vals = ", ".join(f"{hamming[j]:.10f}f" for j in range(i, min(i + 8, WIN_LEN)))
        lines.append(f"    {vals},")

    lines.append("};")
    lines.append("")
    lines.append(
        f"// Mel filterbank matrix [{KWS_FFT_BINS}][{N_MELS}] (float32, transposed for matmul)")
    lines.append("// fbank[i][j] = weight of FFT bin i for Mel band j")
    lines.append("static const float kws_mel_fbank[KWS_FFT_BINS][KWS_N_MELS] = {")

    for i in range(KWS_FFT_BINS):
        vals = ", ".join(f"{filterbank_T[i, j]:.10f}f" for j in range(N_MELS))
        lines.append(f"    {{{vals}}},")

    lines.append("};")
    lines.append("")
    lines.append("#endif /* __KWS_CONSTANTS_H */")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, 'w') as f:
        f.write('\n'.join(lines) + '\n')

    print(f"Generated: {out_path}")
    print(f"  Hamming window: {WIN_LEN} samples ({WIN_LEN*4} B)")
    print(f"  Mel filterbank: {KWS_FFT_BINS}x{N_MELS} ({KWS_FFT_BINS*N_MELS*4} B)")
    print(f"  Total Flash:     ~{(WIN_LEN + KWS_FFT_BINS*N_MELS)*4/1024:.1f} KB")


if __name__ == '__main__':
    generate()
